packages: []
nodeLinker: hoisted
minimumReleaseAge: 4320
overrides:
  '@earendil-works/pi-agent-core': 0.85.1
  '@earendil-works/pi-ai': 0.85.1
  '@earendil-works/pi-tui': 0.85.1
  '@earendil-works/pi-telemetry': 0.85.1
  '@earendil-works/chord': 0.85.1
