export const SAFE_REPO_KEYS = [
  'id',
  'path',
  'displayName',
  'badgeColor',
  'repoIcon',
  'upstream',
  'addedAt',
  'kind',
  'gitUsername',
  'worktreeBaseRef',
  'worktreeBasePath',
  'connectionId',
  'executionHostId',
  'issueSourcePreference',
  'forkSyncMode',
  'externalWorktreeVisibility',
  'externalWorktreeVisibilityLegacy',
  'externalWorktreeVisibilityPromptDismissedAt',
  'externalWorktreeInboxBaselinePaths',
  'importedExternalWorktreePaths',
  'externalWorktreeDiscoverySuppressedAt',
  'symlinkPaths',
  'projectGroupId',
  'projectGroupOrder',
  'projectHostSetupMethod'
] as const

export const SAFE_PROJECT_KEYS = [
  'id',
  'displayName',
  'badgeColor',
  'repoIcon',
  'kind',
  'providerIdentity',
  'localWindowsRuntimePreference',
  'sourceRepoIds',
  'createdAt',
  'updatedAt'
] as const

export const SAFE_PROJECT_HOST_SETUP_KEYS = [
  'id',
  'projectId',
  'hostId',
  'repoId',
  'path',
  'displayName',
  'kind',
  'connectionId',
  'executionHostId',
  'runtimeOwnerEnvironmentId',
  'worktreeBasePath',
  'gitUsername',
  'setupState',
  'setupMethod',
  'createdAt',
  'updatedAt'
] as const

export const SAFE_PROJECT_GROUP_KEYS = [
  'id',
  'name',
  'parentPath',
  'connectionId',
  'executionHostId',
  'parentGroupId',
  'createdFrom',
  'tabOrder',
  'isCollapsed',
  'color',
  'createdAt',
  'updatedAt'
] as const

export const SAFE_FOLDER_WORKSPACE_KEYS = [
  'id',
  'projectGroupId',
  'name',
  'folderPath',
  'connectionId',
  'executionHostId',
  'comment',
  'isArchived',
  'isUnread',
  'isPinned',
  'sortOrder',
  'manualOrder',
  'workspaceStatus',
  'createdWithAgent',
  'pendingFirstAgentMessageRename',
  'firstAgentMessageRenameError',
  'lastActivityAt',
  'createdAt',
  'updatedAt'
] as const

export const SAFE_WORKTREE_META_KEYS = [
  'instanceId',
  'projectId',
  'hostId',
  'projectHostSetupId',
  'displayName',
  'comment',
  'linkedIssue',
  'linkedPR',
  'linkedLinearIssue',
  'linkedLinearIssueWorkspaceId',
  'linkedLinearIssueOrganizationUrlKey',
  'linkedGitLabMR',
  'linkedGitLabIssue',
  'linkedBitbucketPR',
  'linkedAzureDevOpsPR',
  'linkedGiteaPR',
  'isArchived',
  'isUnread',
  'isPinned',
  'sortOrder',
  'manualOrder',
  'lastActivityAt',
  'createdAt',
  'createdWithAgent',
  'pendingFirstAgentMessageRename',
  'firstAgentMessageRenameError',
  'sparseDirectories',
  'sparseBaseRef',
  'sparsePresetId',
  'baseRef',
  'preserveBranchOnDelete',
  'orcaCreatedAt',
  'orcaCreationSource',
  'orcaCreationWorkspaceLayout',
  'workspaceStatus',
  'priorWorktreeIds'
] as const

export const SAFE_SPARSE_PRESET_KEYS = [
  'id',
  'repoId',
  'name',
  'directories',
  'createdAt',
  'updatedAt'
] as const
