export const TASK_NATIVE_DEFAULT_MAX_BYTES = 64 * 1024
export const TASK_WORKFLOW_NATIVE_MAX_BYTES = 1024 * 1024
export const TASK_WORKFLOW_NATIVE_MAX_STRUCTURAL_TOKENS = 65_536
export const TASK_NATIVE_MAX_NESTING_DEPTH = 16
